
- name: "Copy {{ file['path'] }} into the collection directory structure"
  copy:
    src: "{{ file['path'] }}"
    dest: "{{ collection_parent }}/plugins/modules"

- name: Set a fact for the from xxx import xxx statement changes
  set_fact:
    basename: "{{ file['path']|basename }}"
    current: "^from ansible.module_utils{{ source_sub_directory|replace('/', '.') }}"
    new: "from ansible_collections.{{ collection_namespace }}.{{ collection_name }}.plugins.module_utils{{ source_sub_directory|replace('/', '.') }}"

- name: "Update the import statements in {{ collection_parent }}/plugins/modules/{{ basename }}"
  replace:
    path: "{{ collection_parent }}/plugins/modules/{{ basename }}"
    regexp: "{{ current }}"
    replace: "{{ new }}"

- name: "Parse remaining from and import statements"
  set_fact:
    frimports: "{{ file['path']|frimports(frimports|default({}), builtins, default_import_answer|default(omit)) }}"

- name: Include the prompt for frimport
  include: handle_frimport.yml
  with_dict: "{{ frimports }}"
  when: not item['value'] or item['value'] in ['y', 'n', 'Y']
